dropout: 0.2
hidden_dim: 300
lr: 0.001
num_edge_features: 3
num_layers: 5
num_node_features: 9
num_tasks: 128
pos_weights: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCQAAADU1MDUzMjUyOHECWAMAAABjcHVxA0uATnRxBFEugAJdcQBYCQAAADU1MDUzMjUy
    OHEBYS6AAAAAAAAAAO3LHUEAAMhCAADIQgAAyEIAAMhCah0DQmZmMkKGAr5CAADIQgAAyEIAAMhC
    AADIQgAAyEIAAMhCY9utQgAAyEIAAMhCAADIQtFFaUIAAMhCAADIQgAAyEIAAMhCAADIQtNQzUEA
    AMhCLuh4QQAAyEIAAMhCAADIQofnMUIAAMhCAADIQgAAyEIAAMhCkwsFQsekIELFIqFCAADIQgAA
    yEIAAMhCAADIQpFKCEIAAMhCAADIQgAAyEIAAMhCmk0XQTZJrUGfaa9BxWocQkZllUI+xgZCAADI
    QgAAyEIAAMhCAADIQgAAyELUH0BCAADIQkF7R0EAAMhCAADIQgAAyEIAAMhCRJqyQgAAyEI14pFC
    AADIQgAAyEIAAMhCAADIQgAAyEIAAMhCAADIQgAAyEJ9pb5CAADIQgAAyEIAAMhCAADIQnuj+EEu
    yE1CsbpNQkHDw0IAAMhCAADIQrJjS0IAAMhCTSxOQlL1sEIAAMhCzFltQhIffEDT0a5A0HkLQtL0
    gUEAAMhCAADIQgAAyEIAAMhCAADIQgAAyEIAAMhCAADIQgAAyEIAAMhCAADIQgAAyEIAAMhCbKmw
    QDnDCkDZCaRCwWWSQvLShUBaOFNAkhJvQgAAyELiHbpCAADIQquNyUEAAK1BAADIQgAAyEIAAMhC
    AADIQlc2CEIHTcFC
- 0
- !!python/tuple
  - 128
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
