dropout: 0.2
hidden_dim: 300
lr: 0.001
num_edge_features: 3
num_layers: 5
num_node_features: 9
num_tasks: 128
pos_weights: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCgAAADEwMTAyMzM5ODRxAlgDAAAAY3B1cQNLgE50cQRRLoACXXEAWAoAAAAxMDEwMjMz
    OTg0cQFhLoAAAAAAAAAA7csdQQAAyEIAAMhCAADIQgAAyEJqHQNCZmYyQoYCvkIAAMhCAADIQgAA
    yEIAAMhCAADIQgAAyEJj261CAADIQgAAyEIAAMhC0UVpQgAAyEIAAMhCAADIQgAAyEIAAMhC01DN
    QQAAyEIu6HhBAADIQgAAyEIAAMhCh+cxQgAAyEIAAMhCAADIQgAAyEKTCwVCx6QgQsUioUIAAMhC
    AADIQgAAyEIAAMhCkUoIQgAAyEIAAMhCAADIQgAAyEKaTRdBNkmtQZ9pr0HFahxCRmWVQj7GBkIA
    AMhCAADIQgAAyEIAAMhCAADIQtQfQEIAAMhCQXtHQQAAyEIAAMhCAADIQgAAyEJEmrJCAADIQjXi
    kUIAAMhCAADIQgAAyEIAAMhCAADIQgAAyEIAAMhCAADIQn2lvkIAAMhCAADIQgAAyEIAAMhCe6P4
    QS7ITUKxuk1CQcPDQgAAyEIAAMhCsmNLQgAAyEJNLE5CUvWwQgAAyELMWW1CEh98QNPRrkDQeQtC
    0vSBQQAAyEIAAMhCAADIQgAAyEIAAMhCAADIQgAAyEIAAMhCAADIQgAAyEIAAMhCAADIQgAAyEJs
    qbBAOcMKQNkJpELBZZJC8tKFQFo4U0CSEm9CAADIQuIdukIAAMhCq43JQQAArUEAAMhCAADIQgAA
    yEIAAMhCVzYIQgdNwUI=
- 0
- !!python/tuple
  - 128
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
